#!/bin/sh
#Converted from alias after alias got to be too big and convoluted


gpa() {
	GIT_CURRENT=`git branch | grep \* | awk '{print $2}'`
	GIT_CURRENTDIR=`pwd`
	GIT_TOPDIR=`git rev-parse --show-toplevel`
	cd $GIT_TOPDIR

	for x in `git branch | tr -d \* `
		do git checkout $x && git pull
		done
	git checkout master
	cd $GIT_CURRENTDIR
	}

freshen_repos() {
	for repo in *
		do cd $repo
			echo " "
			echo " ======== ${repo} ========= "
			gpa
			cd ../
		done
	}

base="$(basename "$0")"
case $base in
	freshen_repos)
		freshen_repos
	;;
	gpa)
		gpa
	;;
	*)
		echo "Catchall, try again"
	;;
esac
